# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mcpgui.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(496, 597)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(-4, -1, 501, 541))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButtonCreate = QtWidgets.QPushButton(self.tab)
        self.pushButtonCreate.setGeometry(QtCore.QRect(20, 190, 171, 29))
        self.pushButtonCreate.setObjectName("pushButtonCreate")
        self.pushButtonRemove = QtWidgets.QPushButton(self.tab)
        self.pushButtonRemove.setEnabled(False)
        self.pushButtonRemove.setGeometry(QtCore.QRect(20, 230, 171, 29))
        self.pushButtonRemove.setObjectName("pushButtonRemove")
        self.pushButtonSaveCapture = QtWidgets.QPushButton(self.tab)
        self.pushButtonSaveCapture.setEnabled(False)
        self.pushButtonSaveCapture.setGeometry(QtCore.QRect(30, 410, 91, 29))
        self.pushButtonSaveCapture.setObjectName("pushButtonSaveCapture")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 20, 121, 23))
        self.label.setObjectName("label")
        self.spinBoxBuildX = QtWidgets.QSpinBox(self.tab)
        self.spinBoxBuildX.setGeometry(QtCore.QRect(60, 50, 56, 37))
        self.spinBoxBuildX.setMinimum(5)
        self.spinBoxBuildX.setProperty("value", 10)
        self.spinBoxBuildX.setObjectName("spinBoxBuildX")
        self.spinBoxBuildY = QtWidgets.QSpinBox(self.tab)
        self.spinBoxBuildY.setGeometry(QtCore.QRect(150, 50, 56, 37))
        self.spinBoxBuildY.setMinimum(5)
        self.spinBoxBuildY.setProperty("value", 10)
        self.spinBoxBuildY.setObjectName("spinBoxBuildY")
        self.spinBoxBuildZ = QtWidgets.QSpinBox(self.tab)
        self.spinBoxBuildZ.setGeometry(QtCore.QRect(240, 50, 56, 37))
        self.spinBoxBuildZ.setMinimum(5)
        self.spinBoxBuildZ.setProperty("value", 10)
        self.spinBoxBuildZ.setObjectName("spinBoxBuildZ")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(40, 60, 21, 23))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(130, 60, 21, 23))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(220, 60, 21, 23))
        self.label_4.setObjectName("label_4")
        self.spinBoxYOffset = QtWidgets.QSpinBox(self.tab)
        self.spinBoxYOffset.setGeometry(QtCore.QRect(150, 120, 56, 37))
        self.spinBoxYOffset.setMinimum(-50)
        self.spinBoxYOffset.setMaximum(50)
        self.spinBoxYOffset.setProperty("value", 0)
        self.spinBoxYOffset.setObjectName("spinBoxYOffset")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(20, 100, 111, 23))
        self.label_5.setObjectName("label_5")
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(10, 170, 461, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.comboBoxBaseplate = QtWidgets.QComboBox(self.tab)
        self.comboBoxBaseplate.setGeometry(QtCore.QRect(350, 190, 111, 29))
        self.comboBoxBaseplate.setObjectName("comboBoxBaseplate")
        self.comboBoxBaseplate.addItem("")
        self.comboBoxBaseplate.addItem("")
        self.comboBoxBaseplate.addItem("")
        self.comboBoxBaseplate.addItem("")
        self.comboBoxBaseplate.addItem("")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(230, 190, 121, 30))
        self.label_6.setObjectName("label_6")
        self.pushButtonClearArea = QtWidgets.QPushButton(self.tab)
        self.pushButtonClearArea.setEnabled(False)
        self.pushButtonClearArea.setGeometry(QtCore.QRect(20, 300, 161, 29))
        self.pushButtonClearArea.setObjectName("pushButtonClearArea")
        self.pushButtonResetArea = QtWidgets.QPushButton(self.tab)
        self.pushButtonResetArea.setEnabled(False)
        self.pushButtonResetArea.setGeometry(QtCore.QRect(230, 300, 161, 29))
        self.pushButtonResetArea.setObjectName("pushButtonResetArea")
        self.labelBuildareaInfo = QtWidgets.QLabel(self.tab)
        self.labelBuildareaInfo.setGeometry(QtCore.QRect(30, 380, 391, 21))
        self.labelBuildareaInfo.setObjectName("labelBuildareaInfo")
        self.line_3 = QtWidgets.QFrame(self.tab)
        self.line_3.setGeometry(QtCore.QRect(10, 360, 471, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.labelFileSelected = QtWidgets.QLabel(self.tab_2)
        self.labelFileSelected.setGeometry(QtCore.QRect(20, 20, 431, 23))
        self.labelFileSelected.setObjectName("labelFileSelected")
        self.line_2 = QtWidgets.QFrame(self.tab_2)
        self.line_2.setGeometry(QtCore.QRect(10, 150, 471, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_5 = QtWidgets.QFrame(self.tab_2)
        self.line_5.setGeometry(QtCore.QRect(10, 400, 471, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.pushButtonLoadMBFile = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonLoadMBFile.setGeometry(QtCore.QRect(20, 80, 151, 39))
        self.pushButtonLoadMBFile.setObjectName("pushButtonLoadMBFile")
        self.labelFileInformation = QtWidgets.QLabel(self.tab_2)
        self.labelFileInformation.setGeometry(QtCore.QRect(20, 190, 441, 181))
        self.labelFileInformation.setText("")
        self.labelFileInformation.setObjectName("labelFileInformation")
        self.pushButtonSaveSCAD = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonSaveSCAD.setEnabled(False)
        self.pushButtonSaveSCAD.setGeometry(QtCore.QRect(30, 440, 151, 39))
        self.pushButtonSaveSCAD.setObjectName("pushButtonSaveSCAD")
        self.pushButtonSaveSCADAs = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonSaveSCADAs.setEnabled(False)
        self.pushButtonSaveSCADAs.setGeometry(QtCore.QRect(220, 440, 105, 39))
        self.pushButtonSaveSCADAs.setObjectName("pushButtonSaveSCADAs")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(30, 200, 81, 21))
        self.label_7.setObjectName("label_7")
        self.doubleSpinBoxBlockSize = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.doubleSpinBoxBlockSize.setGeometry(QtCore.QRect(110, 190, 72, 30))
        self.doubleSpinBoxBlockSize.setDecimals(1)
        self.doubleSpinBoxBlockSize.setMinimum(1.0)
        self.doubleSpinBoxBlockSize.setProperty("value", 10.0)
        self.doubleSpinBoxBlockSize.setObjectName("doubleSpinBoxBlockSize")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(190, 200, 67, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(30, 250, 71, 21))
        self.label_9.setObjectName("label_9")
        self.labelPrintSize = QtWidgets.QLabel(self.tab_2)
        self.labelPrintSize.setGeometry(QtCore.QRect(90, 290, 361, 21))
        self.labelPrintSize.setObjectName("labelPrintSize")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 496, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionConnect = QtWidgets.QAction(MainWindow)
        self.actionConnect.setObjectName("actionConnect")
        self.menuFile.addAction(self.actionConnect)
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Minecraft Print"))
        self.pushButtonCreate.setText(_translate("MainWindow", "Set build area"))
        self.pushButtonRemove.setText(_translate("MainWindow", "Remove build area"))
        self.pushButtonSaveCapture.setText(_translate("MainWindow", "Save to file"))
        self.label.setText(_translate("MainWindow", "Build area size"))
        self.label_2.setText(_translate("MainWindow", "X"))
        self.label_3.setText(_translate("MainWindow", "Y"))
        self.label_4.setText(_translate("MainWindow", "Z"))
        self.label_5.setText(_translate("MainWindow", "Y axis offset"))
        self.comboBoxBaseplate.setItemText(0, _translate("MainWindow", "Bedrock"))
        self.comboBoxBaseplate.setItemText(1, _translate("MainWindow", "Transparent"))
        self.comboBoxBaseplate.setItemText(2, _translate("MainWindow", "Air"))
        self.comboBoxBaseplate.setItemText(3, _translate("MainWindow", "Obsidian"))
        self.comboBoxBaseplate.setItemText(4, _translate("MainWindow", "Wood"))
        self.label_6.setText(_translate("MainWindow", "Base block type"))
        self.pushButtonClearArea.setText(_translate("MainWindow", "Clear print area"))
        self.pushButtonResetArea.setText(_translate("MainWindow", "Reset build area"))
        self.labelBuildareaInfo.setText(_translate("MainWindow", "Build area is not set"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Minecraft Capture"))
        self.labelFileSelected.setText(_translate("MainWindow", "No file selected"))
        self.pushButtonLoadMBFile.setText(_translate("MainWindow", "Load file"))
        self.pushButtonSaveSCAD.setText(_translate("MainWindow", "Save to OpenSCAD"))
        self.pushButtonSaveSCADAs.setText(_translate("MainWindow", "Save as"))
        self.label_7.setText(_translate("MainWindow", "Block size"))
        self.label_8.setText(_translate("MainWindow", "mm"))
        self.label_9.setText(_translate("MainWindow", "Print size:"))
        self.labelPrintSize.setText(_translate("MainWindow", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "OpenSCAD Export"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.actionQuit.setText(_translate("MainWindow", "&Quit"))
        self.actionConnect.setText(_translate("MainWindow", "Connect"))

